[workspace]
name = "gsw"
version = "0.2.3"
description = "TEOS-10 v3.06.12 Gibbs Seawater Oceanographic Toolbox in Rust"
authors = [
  "Guilherme Castelao <guilherme@castelao.net>",
  "Luiz Irber <github@luizirber.org>"
  ]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64"]

[tasks]

[dependencies]
rust = ">=1.79.0,<1.80"
compilers = ">=1.7.0,<1.8"
clangdev = ">=16.0.6,<17.1"
libclang = ">=16.0.6,<17.1"
cargo-c = "~=0.10.11"
make = ">=4.3,<5"
python = "==3.11"
pytest = ">=8.3.2,<8.4"
dask = ">=2024.7.1,<2024.8"
xarray = ">=2024.6.0,<2024.7"
pip = ">=24.0,<25"
numpy = "<2.0"
pkgconf = ">=2.4.3,<3"
